networks:
  default:
    external: true
    name: roboshop

volumes:
  mongodb:
  redis:
  mysql:
  rabbitmq:

services:
  mongodb:
    image: shan2324/mongodb:v1
    container_name: mongodb
    volumes:
      - mongodb:/data/db
    networks:
      - default

  catalogue:
    image: shan2324/catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb
    networks:
      - default

  redis:
    image: redis:7.0
    container_name: redis
    volumes:
      - redis:/data
    networks:
      - default

  user:
    image: shan2324/user:v1
    container_name: user
    depends_on:
      - redis
      - mongodb
    networks:
      - default

  cart:
    image: shan2324/cart:v1
    container_name: cart
    depends_on:
      - catalogue
      - redis
    networks:
      - default

  mysql:
    image: shan2324/mysql:v1
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - default

  shipping:
    image: shan2324/shipping:v1
    container_name: shipping
    depends_on:
      - mysql
      - cart
    networks:
      - default

  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    networks:
      - default

  payment:
    image: shan2324/payment:v1
    container_name: payment
    environment:
      CART_HOST: cart
      CART_PORT: 8080
      USER_HOST: user
      USER_PORT: 8080
      AMQP_HOST: rabbitmq
      AMQP_USER: roboshop
      AMQP_PASS: roboshop123
    depends_on:
      - rabbitmq
      - cart
      - user
    networks:
      - default
    ports:
      - "8080:8080"

  frontend:
    image: shan2324/frontend:v1
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - catalogue
      - user
      - cart
      - shipping
      - payment
    networks:
      - default